/* Build configuration.
   ------------------------------------------------------------
   baseUrl: the path the site lives at on your server.
     - Hosted at the domain root (https://example.com/)      -> "/"
     - Hosted in a subfolder (https://example.com/sosf/)      -> "/sosf/"
   All asset hrefs and internal links are prefixed with this,
   so generated pages work at whatever depth they sit.
*/
module.exports = {
  // "/" for localhost & Dreamhost root; the GitHub Action overrides it with
  // SITE_BASE_URL="/<repo>/" so GitHub Pages (served at a subpath) works too.
  baseUrl: process.env.SITE_BASE_URL || "/",
  srcDir: "src",
  dataFile: "data/sosf.json",   // generated by `node csv-to-json.js` from data/csv/*
  outDir: "site"
};
